[target.riscv32imafc-unknown-none-elf]
runner = "qemu-system-riscv32 -machine virt -nographic -bios default -serial mon:stdio -kernel"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
]

[build]
target = "riscv32imafc-unknown-none-elf"
